### ISSUE TITLE
Unable to build latest container -- Error in /musicbrainz-server/script/compile_resources.sh

### ISSUE THREAD

**Issue by isuftin** [metabrainz/musicbrainz-docker#14]
Running: `docker-compose run --rm musicbrainz /createdb.sh -fetch`

Error:

```
Step 22 : RUN /musicbrainz-server/script/compile_resources.sh
 ---> Running in f6099aa17eda
Use of uninitialized value $ENV{"DB_ENV_POSTGRES_USER"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_ENV_POSTGRES_PASSWORD"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_PORT_5432_TCP_ADDR"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_PORT_5432_TCP_PORT"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_ENV_POSTGRES_USER"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_ENV_POSTGRES_PASSWORD"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_PORT_5432_TCP_ADDR"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_PORT_5432_TCP_PORT"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_ENV_POSTGRES_USER"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_ENV_POSTGRES_PASSWORD"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_PORT_5432_TCP_ADDR"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Use of uninitialized value $ENV{"DB_PORT_5432_TCP_PORT"} in string at /musicbrainz-server/admin/../lib/DBDefs.pm line 51.
Attribute (port) does not pass the type constraint because: Validation failed for 'Int' with value "" at constructor MusicBrainz::Server::Database::new (defined at /musicbrainz-server/admin/../lib/MusicBrainz/Server/Database.pm line 53) line 52
        MusicBrainz::Server::Database::new('MusicBrainz::Server::Database', 'HASH(0x3c62b00)') called at /musicbrainz-server/admin/../lib/MusicBrainz/Server/DatabaseConnectionFactory.pm line 19
        MusicBrainz::Server::DatabaseConnectionFactory::register_databases('MusicBrainz::Server::DatabaseConnectionFactory', 'READWRITE', 'HASH(0x3c55f00)', 'TEST', 'HASH(0x3c560b0)', 'READONLY', 'HASH(0x3c62b00)', 'SYSTEM', 'HASH(0x3c627a0)') called at /musicbrainz-server/admin/../lib/DBDefs.pm line 51
        require DBDefs.pm at admin/ShowDBDefs line 38
        main::BEGIN at /musicbrainz-server/admin/../lib/DBDefs.pm line 0
        eval {...} at /musicbrainz-server/admin/../lib/DBDefs.pm line 0
Compilation failed in require at admin/ShowDBDefs line 38.
BEGIN failed--compilation aborted at admin/ShowDBDefs line 38.
/musicbrainz-server/root/static/gulpfile.js:4
  throw new Error('error: DEVELOPMENT_SERVER should be set to either 0 or 1');
  ^

Error: error: DEVELOPMENT_SERVER should be set to either 0 or 1
    at Object.<anonymous> (gulpfile.js:2:9)
    at Module._compile (module.js:413:34)
    at loader (/musicbrainz-server/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/musicbrainz-server/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/musicbrainz-server/gulpfile.js:2:1)
    at Module._compile (module.js:413:34)
```

docker-compose.yml:

```
postgresqldata:
  build: data-dockerfile
  restart: always
  volumes:
   - /datadump:/media/dbdump:rw

postgresql:
  build: postgres-dockerfile
  restart: always
  env_file:
   - ./postgres-dockerfile/postgres.env
  expose:
   - "5432"

musicbrainz:
  build: musicbrainz-dockerfile
  ports:
   - "5000:5000"
  volumes_from:
   - postgresqldata
  restart: always
  environment:
   - MUSICBRAINZ_USE_PROXY=1
   - DEVELOPMENT_SERVER=1
  expose:
   - "5000"
  links:
   - postgresql:db
```

```
$ docker --version
Docker version 1.11.1, build 5604cbe

$ docker-compose --version
docker-compose version 1.7.1, build 0a9ab35
```

DBDEFs.pm has `sub DEVELOPMENT_SERVER { 0 }`
