### ISSUE TITLE
Failed to import artist with id in bounds

### ISSUE THREAD

**Issue by PeterCodar** [metabrainz/musicbrainz-docker#159]
The reindex-process seems to start successful for annotations and areas, but for artists I get the following errors:

**2020-06-02 17:17:06,855: Failed to import artist with id in bounds (7646, 31308)
2020-06-02 17:17:06,858: Failed to import artist with id in bounds (43374, 53259)
2020-06-02 17:17:06,860: Failed to import artist with id in bounds (31308, 43374**

Log until the "[No space left on device](https://github.com/metabrainz/musicbrainz-docker/issues/158)" error occurs:
> ubuntu@ubuntu:~/musicbrainz-docker$ sudo docker-compose exec indexer python -m sir reindex
> 2020-06-02 17:14:53,271: Checking whether the versions of the Solr cores are supported
> 2020-06-02 17:14:53,333: Importing annotation...
> 2020-06-02 17:16:38,240: Successfully imported annotation!
> 2020-06-02 17:16:39,127: Importing area...
> 2020-06-02 17:17:06,084: Successfully imported area!
> 2020-06-02 17:17:06,162: Importing artist...
**> 2020-06-02 17:17:06,855: Failed to import artist with id in bounds (7646, 31308)
> 2020-06-02 17:17:06,858: Failed to import artist with id in bounds (43374, 53259)
> 2020-06-02 17:17:06,860: Failed to import artist with id in bounds (31308, 43374)**
> 2020-06-02 17:17:06,856: (psycopg2.OperationalError) could not resize shared memory segment "/PostgreSQL.1034353204" to 196864 bytes: No space left on device
>  [SQL: 'SELECT (SELECT array_agg(musicbrainz.artist_alias.name) AS array_agg_1 \nFROM musicbrainz.artist_alias \nWHERE musicbrainz.artist_alias.artist = musicbrainz.artist.id AND musicbrainz.artist_alias.primary_for_locale = true) AS anon_1, musicbrainz.artist.type AS musicbrainz_artist_type, musicbrainz.artist.area AS musicbrainz_artist_area, musicbrainz.artist.gender AS musicbrainz_artist_gender, musicbrainz.artist.begin_area AS musicbrainz_artist_begin_area, musicbrainz.artist.end_area AS musicbrainz_artist_end_area, musicbrainz.artist.id AS musicbrainz_artist_id, musicbrainz.artist.gid AS musicbrainz_artist_gid, musicbrainz.artist.name AS musicbrainz_artist_name, musicbrainz.artist.sort_name AS musicbrainz_artist_sort_name, musicbrainz.artist.begin_date_year AS musicbrainz_artist_begin_date_year, musicbrainz.artist.begin_date_month AS musicbrainz_artist_begin_date_month, musicbrainz.artist.begin_date_day AS musicbrainz_artist_begin_date_day, musicbrainz.artist.end_date_year AS musicbrainz_artist_end_date_year, musicbrainz.artist.end_date_month AS musicbrainz_artist_end_date_month, musicbrainz.artist.end_date_day AS musicbrainz_artist_end_date_day, musicbrainz.artist.comment AS musicbrainz_artist_comment, musicbrainz.artist.edits_pending AS musicbrainz_artist_edits_pending, musicbrainz.artist.last_updated AS musicbrainz_artist_last_updated, musicbrainz.artist.ended AS musicbrainz_artist_ended, area_1.type ....

**Comment by brady1408** [comment]
This is a problem with the default shared memory value in docker, I had the same issue and resolved it by adding a shm_size line to my docker-compose.yml to match the size of what is configured inside of postgres

[This](https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device) thead was helpful in resolving this for me

Code Snip
```yaml
services:
  db:
    build:
      context: build/postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-12}
    image: musicbrainz-docker_db:${POSTGRES_VERSION:-12}
    shm_size: 2g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: unless-stopped
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so"
```
