### ISSUE TITLE
How can I use a mirror server without Indexed Search ?

### ISSUE THREAD

**Issue by niko2** [metabrainz/musicbrainz-docker#164]
Hello,
I cannot find answer neither in docs nor in forums.
You mention in the README (about HW needed), that MB can be deployed without the indexed search.
How can I do that ?
Thank you for your answer.

**Comment by yvanzo** [comment]
Hi,

Create a [Docker Compose override](https://github.com/metabrainz/musicbrainz-docker#docker-compose-overrides) file `local/compose/remote-search.yml`:

```yml
version: '3.1'

# Description: Use remote search server

services:
  musicbrainz:
    environment:
      - MUSICBRAINZ_SEARCH_SERVER=search.musicbrainz.org
```

Then enable it by running:

```bash
admin/configure add local/compose/remote-search.yml
sudo docker-compose up -d
```

Note that the services `mq` and `search` will still be started but not used.
