### ISSUE TITLE
Optimize Postgres v12 Memory Parameters (memory-settings.yml)

### ISSUE THREAD

**Issue by JoshDi** [metabrainz/musicbrainz-docker#166]
I have changed some of my Postgres v12 Memory Parameters (memory-settings.yml) and noticed that live indexing search is working better. Here are the settings I am now using. 

Does anyone have any suggestions? I am running my Musicbrainz replication server on a server with 24c/48t and 128gb of ram. Thank you!

**local/compose/memory-settings.yml**
```
version: '3.1'

# Description: Customize memory settings

services:
  db:
    shm_size: 4g
    command: postgres -c "shared_buffers=4GB" -c "work_mem=128MB" -c "maintenance_work_mem=4GB" -c "effective_cache_size=64GB" -c "shared_preload_libraries=pg_amqp.so"
  search:
    environment:
      - SOLR_HEAP=4g
```
