### ISSUE TITLE
Issue Building Indexes

### ISSUE THREAD

**Issue by GL-Doses** [metabrainz/musicbrainz-docker#240]
I was following the instructions here, and the only difference was that I mounted some directories for persistent data.
Everything was successful until I try to build indexes with:
`sudo docker-compose exec indexer python -m sir reindex`
The error message was:

Checking whether the versions of the Solr cores are supported
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/code/sir/__main__.py", line 134, in <module>
    main()
  File "/code/sir/__main__.py", line 130, in main
    func(args)
  File "sir/indexing.py", line 54, in reindex
    util.check_solr_cores_version(entities)
  File "sir/util.py", line 123, in check_solr_cores_version
    map(solr_version_check, cores)
  File "sir/util.py", line 106, in solr_version_check
    u = urllib2.urlopen("%s/%s/schema/version" % (solr_uri, core))
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Server Error
ERROR: 1

Any help is welcome. Thanks.

**Comment by yvanzo** [comment]
The error code lets think that the `indexer` is unable to find the `search` server, most likely because it was not running or it was unable to start properly. You might want to check logs (`docker-compose --timestamps logs search`) to get more info.

Please provide your configuration details:
```sh
echo MusicBrainz Docker: `git describe --always --broken --dirty --tags`
echo Docker Compose: `docker-compose version --short`
sudo docker version -f 'Docker Client/Server: {{.Client.Version}}/{{.Server.Version}}'
./admin/configure show
docker-compose config
```

**Comment by GL-Doses** [comment]
Here is the info that you asked for:

- git describe --always --broken --dirty --tags
`I did not used git. I downloaded the repository here on github and put all files in a folder.`


- docker-compose version --short
`1.28.5`


- docker version -f 'Docker Client/Server: {{.Client.Version}}/{{.Server.Version}}'
`Docker Client/Server: 20.10.3/20.10.3`


- docker-compose config
(As you can see below I edited the volumes)
```
services:
  db:
    build:
      args:
        POSTGRES_VERSION: '12'
      context: /volume1/docker/musicbrainz-server/build/postgres
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so"
    environment:
      POSTGRES_PASSWORD: musicbrainz
      POSTGRES_USER: musicbrainz
    expose:
    - '5432'
    image: musicbrainz-docker_db:12
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    restart: unless-stopped
    shm_size: 2GB
    volumes:
    - /volume1/docker/musicbrainz-server/pgdata:/var/lib/postgresql/data:rw
  indexer:
    build:
      context: /volume1/docker/musicbrainz-server/build/sir
    depends_on:
      db:
        condition: service_started
      mq:
        condition: service_started
      search:
        condition: service_started
    environment:
      POSTGRES_PASSWORD: musicbrainz
      POSTGRES_USER: musicbrainz
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    volumes:
    - /volume1/docker/musicbrainz-server/default/indexer.ini:/code/config.ini:rw
  mq:
    build:
      context: /volume1/docker/musicbrainz-server/build/rabbitmq
    expose:
    - '5672'
    hostname: mq
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    restart: unless-stopped
    volumes:
    - /volume1/docker/musicbrainz-server/mqdata:/var/lib/rabbitmq:rw
  musicbrainz:
    build:
      args:
        POSTGRES_VERSION: '12'
      context: /volume1/docker/musicbrainz-server/build/musicbrainz
    depends_on:
      db:
        condition: service_started
      mq:
        condition: service_started
      redis:
        condition: service_started
      search:
        condition: service_started
    environment:
      MUSICBRAINZ_BASE_FTP_URL: ftp://ftp.eu.metabrainz.org/pub/musicbrainz
      MUSICBRAINZ_SERVER_PROCESSES: '10'
      MUSICBRAINZ_USE_PROXY: '1'
      MUSICBRAINZ_WEB_SERVER_HOST: localhost
      MUSICBRAINZ_WEB_SERVER_PORT: '5000'
      POSTGRES_PASSWORD: musicbrainz
      POSTGRES_USER: musicbrainz
    logging:
      driver: json-file
      options:
        max-file: '50'
        max-size: 50m
    ports:
    - published: 5000
      target: 5000
    restart: unless-stopped
    volumes:
    - /volume1/docker/musicbrainz-server/dbdump:/media/dbdump:rw
    - /volume1/docker/musicbrainz-server/searchdump:/media/searchdump:rw
  redis:
    expose:
    - '6379'
    image: redis:3-alpine
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    restart: unless-stopped
  search:
    build:
      args:
        MB_SOLR_VERSION: 3.4.2
      context: /volume1/docker/musicbrainz-server/build/solr
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
      SOLR_HEAP: 2g
    expose:
    - '8983'
    image: musicbrainz-docker_search:3.4.2
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 10m
    restart: unless-stopped
    volumes:
    - /volume1/docker/musicbrainz-server/solrdata:/opt/solr/server/solr/data:rw
    - /volume1/docker/musicbrainz-server/searchdump:/media/searchdump:rw
version: '3.1'
```
