### ISSUE TITLE
'load-search-indexes.sh' fails with '/media/searchdump/*.tar.zst: Cannot open: No such file or directory'

### ISSUE THREAD

**Issue by hilbertglm** [metabrainz/musicbrainz-docker#296]
I was following the steps to set up search indexes via the command:

sudo docker compose run --rm search load-search-indexes.sh

and received the error:

Thu Feb 20 15:22:58 UTC 2025: Load * search index...
tar (child): /media/searchdump/*.tar.zst: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

The problem was a file permission problem on the /media/searchdump directory.  I think I was running as the user 'solr', and needed to be 'root'.  It appears to be loading now when I took the following steps:

- sudo docker exec -it --user root musicbrainz-docker-search-1 bash
- load-search-indexes.sh

It think I could also have added the '--user root' to the 'docker compose run...' command, but I did not test that.

**Comment by yvanzo** [comment]
Hi @hilbertglm, loading search indexes is working for others and I’m unable to reproduce this error. Yes the files are belong to the user `root` but they are readable by the user `solr` in my experience.

The error you are reporting has something to do with your setup, most likely with the way the Docker volumes are handled by your host system.

- What is the host system?
- What are your Docker/Compose versions?

**Comment by hilbertglm** [comment]
Sorry about that.  I even ran the command and forgot to paste it in:

MusicBrainz Docker: v-2025-02-10.0-dirty
Docker Compose: 2.5.0
Docker Client/Server: 24.0.2/24.0.2

The change I made was to the volumes for space reasons.  I will look into that as a possible cause.  Thanks

```
volumes:
  mqdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/data/musicbrainz/musicbrainz-docker_mqdata'
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/data/musicbrainz/musicbrainz-docker_pgdata'
  solrdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/data/musicbrainz/musicbrainz-docker_solrdata'
  dbdump:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/data/musicbrainz/musicbrainz-docker_dbdump'
  searchdump:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/data/musicbrainz/musicbrainz-docker_searchdump'


```
